metadatablock.name=dansMetadata
metadatablock.displayName=DANS Specific metadata
metadatablock.displayFacet=DANS metadata
datasetfieldtype.dansTemporalCoverage.title=Temporal Coverage
datasetfieldtype.dansRightsHolder.title=Rights Holder
datasetfieldtype.dansPersonalDataPresent.title=Personal Data In Dataset?
datasetfieldtype.dansMetadataLanguage.title=Language Of Metadata
datasetfieldtype.dansAudience.title=Audience
datasetfieldtype.dansCollection.title=Collection
datasetfieldtype.dansRelation.title=Relation or Related Material
datasetfieldtype.dansRelationType.title=Type
datasetfieldtype.dansRelationText.title=Text
datasetfieldtype.dansRelationURI.title=URI
datasetfieldtype.dansElsstClassification.title=Keyword ELSST
datasetfieldtype.dansCessdaClassification.title=Topic Classification CESSDA
datasetfieldtype.dansTemporalCoverage.description=Enter a year or a historical period keyword to which the data relate. Examples: 1595; Renaissance	
datasetfieldtype.dansRightsHolder.description=State the organisation or individual that is holder of the intellectual property rights. For datasets, these rights are usually vested in the organisation that employs the data creator(s).	
datasetfieldtype.dansPersonalDataPresent.description=DANS needs to know whether your dataset contains personal data in the sense of the General Data Protection Regulation (GDPR).	
datasetfieldtype.dansMetadataLanguage.description=Specify which language was used to describe this dataset
datasetfieldtype.dansAudience.description=Use autocomplete to select the scientific disciplines to which the dataset is relevant.	
datasetfieldtype.dansCollection.description=Use autocomplete to add the dataset to the collection of all datasets from a certain organisation.	
datasetfieldtype.dansRelation.description=Enter the details of a related dataset or other source	
datasetfieldtype.dansRelationType.description=Specify the type of relation between the current dataset and the related source. See https://www.dublincore.org/specifications/dublin-core/rdf-relation-types/, use 'Relation' if the relation type cannot be described with any of the other available qualifiers.	
datasetfieldtype.dansRelationText.description=Enter the title of the related dataset or other source	
datasetfieldtype.dansRelationURI.description=Enter the hyperlink of the related dataset or other source. Use a Persistent Identifier when possible.	
datasetfieldtype.dansElsstClassification.description=A key term from the European Language Social Science Thesaurus (ELSST) that describes an important aspect of the Dataset.	
datasetfieldtype.dansCessdaClassification.description=Indicates a broad, important topic selected from the CESSDA Topic Classification that the Dataset covers.	
datasetfieldtype.dansTemporalCoverage.watermark=
datasetfieldtype.dansRightsHolder.watermark=
datasetfieldtype.dansPersonalDataPresent.watermark=
datasetfieldtype.dansMetadataLanguage.watermark=
datasetfieldtype.dansAudience.watermark=
datasetfieldtype.dansCollection.watermark=
datasetfieldtype.dansRelation.watermark=
datasetfieldtype.dansRelationType.watermark=
datasetfieldtype.dansRelationText.watermark=
datasetfieldtype.dansRelationURI.watermark=
datasetfieldtype.dansElsstClassification.watermark=
datasetfieldtype.dansCessdaClassification.watermark=
datasetfieldtype.dansRightsHolder=Rights Holder
datasetfieldtype.dansPersonalDataPresent=Personal Data In Dataset?
datasetfieldtype.dansMetadataLanguage=Language Of Metadata
controlledvocabulary.dansPersonalDataPresent.yes=Yes
controlledvocabulary.dansPersonalDataPresent.no=No
controlledvocabulary.dansPersonalDataPresent.unknown=Unknown
controlledvocabulary.dansMetadataLanguage.abkhaz=Abkhaz
controlledvocabulary.dansMetadataLanguage.afar=Afar
controlledvocabulary.dansMetadataLanguage.afrikaans=Afrikaans
controlledvocabulary.dansMetadataLanguage.akan=Akan
controlledvocabulary.dansMetadataLanguage.albanian=Albanian
controlledvocabulary.dansMetadataLanguage.amharic=Amharic
controlledvocabulary.dansMetadataLanguage.arabic=Arabic
controlledvocabulary.dansMetadataLanguage.aragonese=Aragonese
controlledvocabulary.dansMetadataLanguage.armenian=Armenian
controlledvocabulary.dansMetadataLanguage.assamese=Assamese
controlledvocabulary.dansMetadataLanguage.avaric=Avaric
controlledvocabulary.dansMetadataLanguage.avestan=Avestan
controlledvocabulary.dansMetadataLanguage.aymara=Aymara
controlledvocabulary.dansMetadataLanguage.azerbaijani=Azerbaijani
controlledvocabulary.dansMetadataLanguage.bambara=Bambara
controlledvocabulary.dansMetadataLanguage.bashkir=Bashkir
controlledvocabulary.dansMetadataLanguage.basque=Basque
controlledvocabulary.dansMetadataLanguage.belarusian=Belarusian
controlledvocabulary.dansMetadataLanguage.bengali,_bangla=Bengali, Bangla
controlledvocabulary.dansMetadataLanguage.bihari=Bihari
controlledvocabulary.dansMetadataLanguage.bislama=Bislama
controlledvocabulary.dansMetadataLanguage.bosnian=Bosnian
controlledvocabulary.dansMetadataLanguage.breton=Breton
controlledvocabulary.dansMetadataLanguage.bulgarian=Bulgarian
controlledvocabulary.dansMetadataLanguage.burmese=Burmese
controlledvocabulary.dansMetadataLanguage.catalan,valencian=Catalan,Valencian
controlledvocabulary.dansMetadataLanguage.chamorro=Chamorro
controlledvocabulary.dansMetadataLanguage.chechen=Chechen
controlledvocabulary.dansMetadataLanguage.chichewa,_chewa,_nyanja=Chichewa, Chewa, Nyanja
controlledvocabulary.dansMetadataLanguage.chinese=Chinese
controlledvocabulary.dansMetadataLanguage.chuvash=Chuvash
controlledvocabulary.dansMetadataLanguage.cornish=Cornish
controlledvocabulary.dansMetadataLanguage.corsican=Corsican
controlledvocabulary.dansMetadataLanguage.cree=Cree
controlledvocabulary.dansMetadataLanguage.croatian=Croatian
controlledvocabulary.dansMetadataLanguage.czech=Czech
controlledvocabulary.dansMetadataLanguage.danish=Danish
controlledvocabulary.dansMetadataLanguage.divehi,_dhivehi,_maldivian=Divehi, Dhivehi, Maldivian
controlledvocabulary.dansMetadataLanguage.dutch=Dutch
controlledvocabulary.dansMetadataLanguage.dzongkha=Dzongkha
controlledvocabulary.dansMetadataLanguage.english=English
controlledvocabulary.dansMetadataLanguage.esperanto=Esperanto
controlledvocabulary.dansMetadataLanguage.estonian=Estonian
controlledvocabulary.dansMetadataLanguage.ewe=Ewe
controlledvocabulary.dansMetadataLanguage.faroese=Faroese
controlledvocabulary.dansMetadataLanguage.fijian=Fijian
controlledvocabulary.dansMetadataLanguage.finnish=Finnish
controlledvocabulary.dansMetadataLanguage.french=French
controlledvocabulary.dansMetadataLanguage.fula,_fulah,_pulaar,_pular=Fula, Fulah, Pulaar, Pular
controlledvocabulary.dansMetadataLanguage.galician=Galician
controlledvocabulary.dansMetadataLanguage.georgian=Georgian
controlledvocabulary.dansMetadataLanguage.german=German
controlledvocabulary.dansMetadataLanguage.greek_(modern)=Greek (modern)
controlledvocabulary.dansMetadataLanguage.guarani=GuaranÃ­
controlledvocabulary.dansMetadataLanguage.gujarati=Gujarati
controlledvocabulary.dansMetadataLanguage.haitian,_haitian_creole=Haitian, Haitian Creole
controlledvocabulary.dansMetadataLanguage.hausa=Hausa
controlledvocabulary.dansMetadataLanguage.hebrew_(modern)=Hebrew (modern)
controlledvocabulary.dansMetadataLanguage.herero=Herero
controlledvocabulary.dansMetadataLanguage.hindi=Hindi
controlledvocabulary.dansMetadataLanguage.hiri_motu=Hiri Motu
controlledvocabulary.dansMetadataLanguage.hungarian=Hungarian
controlledvocabulary.dansMetadataLanguage.interlingua=Interlingua
controlledvocabulary.dansMetadataLanguage.indonesian=Indonesian
controlledvocabulary.dansMetadataLanguage.interlingue=Interlingue
controlledvocabulary.dansMetadataLanguage.irish=Irish
controlledvocabulary.dansMetadataLanguage.igbo=Igbo
controlledvocabulary.dansMetadataLanguage.inupiaq=Inupiaq
controlledvocabulary.dansMetadataLanguage.ido=Ido
controlledvocabulary.dansMetadataLanguage.icelandic=Icelandic
controlledvocabulary.dansMetadataLanguage.italian=Italian
controlledvocabulary.dansMetadataLanguage.inuktitut=Inuktitut
controlledvocabulary.dansMetadataLanguage.japanese=Japanese
controlledvocabulary.dansMetadataLanguage.javanese=Javanese
controlledvocabulary.dansMetadataLanguage.kalaallisut,_greenlandic=Kalaallisut, Greenlandic
controlledvocabulary.dansMetadataLanguage.kannada=Kannada
controlledvocabulary.dansMetadataLanguage.kanuri=Kanuri
controlledvocabulary.dansMetadataLanguage.kashmiri=Kashmiri
controlledvocabulary.dansMetadataLanguage.kazakh=Kazakh
controlledvocabulary.dansMetadataLanguage.khmer=Khmer
controlledvocabulary.dansMetadataLanguage.kikuyu,_gikuyu=Kikuyu, Gikuyu
controlledvocabulary.dansMetadataLanguage.kinyarwanda=Kinyarwanda
controlledvocabulary.dansMetadataLanguage.kyrgyz=Kyrgyz
controlledvocabulary.dansMetadataLanguage.komi=Komi
controlledvocabulary.dansMetadataLanguage.kongo=Kongo
controlledvocabulary.dansMetadataLanguage.korean=Korean
controlledvocabulary.dansMetadataLanguage.kurdish=Kurdish
controlledvocabulary.dansMetadataLanguage.kwanyama,_kuanyama=Kwanyama, Kuanyama
controlledvocabulary.dansMetadataLanguage.latin=Latin
controlledvocabulary.dansMetadataLanguage.luxembourgish,_letzeburgesch=Luxembourgish, Letzeburgesch
controlledvocabulary.dansMetadataLanguage.ganda=Ganda
controlledvocabulary.dansMetadataLanguage.limburgish,_limburgan,_limburger=Limburgish, Limburgan, Limburger
controlledvocabulary.dansMetadataLanguage.lingala=Lingala
controlledvocabulary.dansMetadataLanguage.lao=Lao
controlledvocabulary.dansMetadataLanguage.lithuanian=Lithuanian
controlledvocabulary.dansMetadataLanguage.luba-katanga=Luba-Katanga
controlledvocabulary.dansMetadataLanguage.latvian=Latvian
controlledvocabulary.dansMetadataLanguage.manx=Manx
controlledvocabulary.dansMetadataLanguage.macedonian=Macedonian
controlledvocabulary.dansMetadataLanguage.malagasy=Malagasy
controlledvocabulary.dansMetadataLanguage.malay=Malay
controlledvocabulary.dansMetadataLanguage.malayalam=Malayalam
controlledvocabulary.dansMetadataLanguage.maltese=Maltese
controlledvocabulary.dansMetadataLanguage.maori=MÄori
controlledvocabulary.dansMetadataLanguage.marathi_(marathi)=Marathi (MarÄá¹­hÄ«)
controlledvocabulary.dansMetadataLanguage.marshallese=Marshallese
controlledvocabulary.dansMetadataLanguage.mixtepec_mixtec=Mixtepec Mixtec
controlledvocabulary.dansMetadataLanguage.mongolian=Mongolian
controlledvocabulary.dansMetadataLanguage.nauru=Nauru
controlledvocabulary.dansMetadataLanguage.navajo,_navaho=Navajo, Navaho
controlledvocabulary.dansMetadataLanguage.northern_ndebele=Northern Ndebele
controlledvocabulary.dansMetadataLanguage.nepali=Nepali
controlledvocabulary.dansMetadataLanguage.ndonga=Ndonga
controlledvocabulary.dansMetadataLanguage.norwegian_bokmal=Norwegian BokmÃ¥l
controlledvocabulary.dansMetadataLanguage.norwegian_nynorsk=Norwegian Nynorsk
controlledvocabulary.dansMetadataLanguage.norwegian=Norwegian
controlledvocabulary.dansMetadataLanguage.nuosu=Nuosu
controlledvocabulary.dansMetadataLanguage.southern_ndebele=Southern Ndebele
controlledvocabulary.dansMetadataLanguage.occitan=Occitan
controlledvocabulary.dansMetadataLanguage.ojibwe,_ojibwa=Ojibwe, Ojibwa
controlledvocabulary.dansMetadataLanguage.old_church_slavonic,church_slavonic,old_bulgarian=Old Church Slavonic,Church Slavonic,Old Bulgarian
controlledvocabulary.dansMetadataLanguage.oromo=Oromo
controlledvocabulary.dansMetadataLanguage.oriya=Oriya
controlledvocabulary.dansMetadataLanguage.ossetian,_ossetic=Ossetian, Ossetic
controlledvocabulary.dansMetadataLanguage.panjabi,_punjabi=Panjabi, Punjabi
controlledvocabulary.dansMetadataLanguage.pali=PÄli
controlledvocabulary.dansMetadataLanguage.persian_(farsi)=Persian (Farsi)
controlledvocabulary.dansMetadataLanguage.polish=Polish
controlledvocabulary.dansMetadataLanguage.pashto,_pushto=Pashto, Pushto
controlledvocabulary.dansMetadataLanguage.portuguese=Portuguese
controlledvocabulary.dansMetadataLanguage.quechua=Quechua
controlledvocabulary.dansMetadataLanguage.romansh=Romansh
controlledvocabulary.dansMetadataLanguage.kirundi=Kirundi
controlledvocabulary.dansMetadataLanguage.romanian=Romanian
controlledvocabulary.dansMetadataLanguage.russian=Russian
controlledvocabulary.dansMetadataLanguage.sanskrit_(samskrta)=Sanskrit (Saá¹ská¹ta)
controlledvocabulary.dansMetadataLanguage.sardinian=Sardinian
controlledvocabulary.dansMetadataLanguage.sindhi=Sindhi
controlledvocabulary.dansMetadataLanguage.northern_sami=Northern Sami
controlledvocabulary.dansMetadataLanguage.samoan=Samoan
controlledvocabulary.dansMetadataLanguage.sango=Sango
controlledvocabulary.dansMetadataLanguage.serbian=Serbian
controlledvocabulary.dansMetadataLanguage.scottish_gaelic,_gaelic=Scottish Gaelic, Gaelic
controlledvocabulary.dansMetadataLanguage.shona=Shona
controlledvocabulary.dansMetadataLanguage.sinhala,_sinhalese=Sinhala, Sinhalese
controlledvocabulary.dansMetadataLanguage.slovak=Slovak
controlledvocabulary.dansMetadataLanguage.slovene=Slovene
controlledvocabulary.dansMetadataLanguage.somali=Somali
controlledvocabulary.dansMetadataLanguage.southern_sotho=Southern Sotho
controlledvocabulary.dansMetadataLanguage.spanish,_castilian=Spanish, Castilian
controlledvocabulary.dansMetadataLanguage.sundanese=Sundanese
controlledvocabulary.dansMetadataLanguage.swahili=Swahili
controlledvocabulary.dansMetadataLanguage.swati=Swati
controlledvocabulary.dansMetadataLanguage.swedish=Swedish
controlledvocabulary.dansMetadataLanguage.tamil=Tamil
controlledvocabulary.dansMetadataLanguage.telugu=Telugu
controlledvocabulary.dansMetadataLanguage.tajik=Tajik
controlledvocabulary.dansMetadataLanguage.thai=Thai
controlledvocabulary.dansMetadataLanguage.tigrinya=Tigrinya
controlledvocabulary.dansMetadataLanguage.tibetan_standard,_tibetan,_central=Tibetan Standard, Tibetan, Central
controlledvocabulary.dansMetadataLanguage.turkmen=Turkmen
controlledvocabulary.dansMetadataLanguage.tagalog=Tagalog
controlledvocabulary.dansMetadataLanguage.tswana=Tswana
controlledvocabulary.dansMetadataLanguage.tonga_(tonga_islands)=Tonga (Tonga Islands)
controlledvocabulary.dansMetadataLanguage.turkish=Turkish
controlledvocabulary.dansMetadataLanguage.tsonga=Tsonga
controlledvocabulary.dansMetadataLanguage.tatar=Tatar
controlledvocabulary.dansMetadataLanguage.twi=Twi
controlledvocabulary.dansMetadataLanguage.tahitian=Tahitian
controlledvocabulary.dansMetadataLanguage.uyghur,_uighur=Uyghur, Uighur
controlledvocabulary.dansMetadataLanguage.ukrainian=Ukrainian
controlledvocabulary.dansMetadataLanguage.urdu=Urdu
controlledvocabulary.dansMetadataLanguage.uzbek=Uzbek
controlledvocabulary.dansMetadataLanguage.venda=Venda
controlledvocabulary.dansMetadataLanguage.vietnamese=Vietnamese
controlledvocabulary.dansMetadataLanguage.volapuk=VolapÃ¼k
controlledvocabulary.dansMetadataLanguage.walloon=Walloon
controlledvocabulary.dansMetadataLanguage.welsh=Welsh
controlledvocabulary.dansMetadataLanguage.wolof=Wolof
controlledvocabulary.dansMetadataLanguage.western_frisian=Western Frisian
controlledvocabulary.dansMetadataLanguage.xhosa=Xhosa
controlledvocabulary.dansMetadataLanguage.yiddish=Yiddish
controlledvocabulary.dansMetadataLanguage.yoruba=Yoruba
controlledvocabulary.dansMetadataLanguage.zhuang,_chuang=Zhuang, Chuang
controlledvocabulary.dansMetadataLanguage.zulu=Zulu
controlledvocabulary.dansMetadataLanguage.not_applicable=Not applicable
