metadatablock.name=enrichments
metadatablock.displayName=Enriched Metadata
metadatablock.displayFacet=Enriched Metadata
datasetfieldtype.enrichedElsstClassification.title=Keyword ELSST
datasetfieldtype.enrichedCbsTaxonomyTerm.title=Taxonomy CBS
datasetfieldtype.enrichedCbsConcept.title=Concept CBS
datasetfieldtype.frequencyOfUse.title=Frequency of Use
datasetfieldtype.cbsLinkage.title=Linkage to CBS Microdata
datasetfieldtype.cbsLinkageDetails.title=Linkage Details
datasetfieldtype.enrichedElsstClassification.description=This field contains an ELSST (European Language Social Science Thesaurus) term matched to a keyword or other term present in the original metadata.
datasetfieldtype.cbsTaxonomyVocURL.description=A term from the CBS Taxonomy.
datasetfieldtype.enrichedCbsConcept.description=A concept from the CBS Concepts Vocabulary.
datasetfieldtype.frequencyOfUse.description=The frequency of use of a data file among CBS RA projects.
datasetfieldtype.cbsLinkage.description=The linkage of the dataset with CBS microdata.
datasetfieldtype.cbsLinkageDetails.description=	Additional details on the CBS microdata linkage.
datasetfieldtype.enrichedElsstClassification.watermark=
datasetfieldtype.enrichedCbsTaxonomyTerm.watermark=
datasetfieldtype.enrichedCbsConcept.watermark=
datasetfieldtype.frequencyOfUse.watermark=
datasetfieldtype.cbsLinkage.watermark=
datasetfieldtype.elsstVarLabel3.watermark=
datasetfieldtype.cbsLinkageDetails.watermark=








